### ISSUE TITLE
Tagged version release

### ISSUE THREAD

**Issue by peterholak** [evert/SabreAMF#6]
Right now, the only version of this package on packagist.org is dev/master (https://packagist.org/packages/sabre/amf). This means that if I want to have a package that depends on some other package that in turn depends on SabreAMF, composer will refuse to install it unless minimum-stability is set to dev in my composer.json file, which I would rather not do.

All that needs to be done to address this is to create a git tag with the version number, which packagist will then automatically load and process.

**Comment by orlitzky** [comment]
The other place to get a "real" release is Google Code, which is going to be shut down at the end of 2016. We have SabreAMF available in Gentoo, and would like to have another place to get a release, too.

**Comment by evert** [comment]
I just tagged 1.5.0. Straight up from master.

Curious who still uses this though. This package is quite old. Are there people depending on it in Gentoo?

**Comment by orlitzky** [comment]
I honestly don't know. We're trying to clean up all of our googlecode.com references, and this is an easy fix, so I figured I'd fix it. The package was originally added before we used Git, and finding out why it was added is more archaeology than I'm up for =)

**Comment by evert** [comment]
Fair enough =)
